FROM python:latest
ARG BUILD_DATE

LABEL build_version="Build-date:- ${BUILD_DATE}"
LABEL maintainer="Daniel Hufschläger"


COPY app/database.db ./app/
COPY backend_scripts/app_backend.py ./app/
COPY requirements.txt ./app/
COPY backend_scripts/entrypointbe.sh ./app/entrypoint.sh

RUN pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir -r ./app/requirements.txt

RUN chmod +x ./app/entrypoint.sh

ENTRYPOINT ["python", "./app/app_backend.py"]